// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"
	record "playlist-saver/model/record"

	mock "github.com/stretchr/testify/mock"
)

// PlaylistDetailRepository is an autogenerated mock type for the PlaylistDetailRepository type
type PlaylistDetailRepository struct {
	mock.Mock
}

// AddYoutubeToPlaylist provides a mock function with given fields: ctx, data
func (_m *PlaylistDetailRepository) AddYoutubeToPlaylist(ctx context.Context, data record.PlaylistDetail) record.PlaylistDetail {
	ret := _m.Called(ctx, data)

	var r0 record.PlaylistDetail
	if rf, ok := ret.Get(0).(func(context.Context, record.PlaylistDetail) record.PlaylistDetail); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(record.PlaylistDetail)
	}

	return r0
}

// DeleteYoutubeDataFromPlaylist provides a mock function with given fields: ctx, id
func (_m *PlaylistDetailRepository) DeleteYoutubeDataFromPlaylist(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
